### ISSUE TITLE
Missing GLIBC_2.33 with build 0.0.1-alpha1

### ISSUE THREAD

**Issue by Laykeen** [Oples/tf2-stats#7]
**Current System:**
- Ubuntu 20.04.3 LTS x86_64
- kernel 5.11.0-41-generic
- AMD Ryzen 7 2700X (16) @ 3.700GHz
- dev tools for c++ and nim installed

---

**How to reproduce the problem:**

Running `./TF2-Stats-GUI` from the downloaded TF2-Stats-linux-x86-64.zip from [https://github.com/Oples/tf2-stats/releases/tag/0.0.1-alpha1](https://github.com/Oples/tf2-stats/releases/tag/0.0.1-alpha1) gives the following error: 
```./TF2-Stats-GUI: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./TF2-Stats-GUI)```

---

**Comment:**
Maybe a test build on every system?

**Comment by Oples** [comment]
> Missing GLIBC_2.33 with build 0.0.1-alpha1

Solution: Update your system
```bash
pacman -Syu
```

> Maybe a test build on every system?

I will make an other issue for that but building a CI/CD setup is not a priority
